### ISSUE TITLE
Crash when attempted to set lava as a lightblock 

### ISSUE THREAD

**Issue by Saereth** [Low-Drag-MC/Shimmer#3]
`[03:52:04] [Render thread/ERROR]: Unreported exception thrown!
java.nio.BufferOverflowException: null
	at java.nio.FloatBuffer.put(FloatBuffer.java:1179) ~[?:?]
	at java.nio.FloatBuffer.put(FloatBuffer.java:1210) ~[?:?]
	at com.lowdragmc.shimmer.client.light.ColorPointLight.uploadBuffer(ColorPointLight.java:83) ~[shimmer-1.18.2-0.1.jar%23188!/:1.18.2-0.1]
	at com.lowdragmc.shimmer.client.light.LightManager.renderLevelPre(LightManager.java:94) ~[shimmer-1.18.2-0.1.jar%23188!/:1.18.2-0.1]
	at net.minecraft.client.renderer.LevelRenderer.handler$zpo000$injectRenderLevelPre(LevelRenderer.java:8077) ~[client-1.18.2-20220404.173914-srg.jar%23224!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java) ~[client-1.18.2-20220404.173914-srg.jar%23224!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1059) ~[client-1.18.2-20220404.173914-srg.jar%23224!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:833) ~[client-1.18.2-20220404.173914-srg.jar%23224!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23224!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23224!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23224!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.20.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[03:52:05] [Server thread/INFO]: Stopping server
[03:52:05] [Server thread/INFO]: Saving players`

Getting this crash now after adding lava as a lightblock in the nether. 

here is my config 

```
{
  "LightBlock": [
      {
      "block": "minecraft:lava",
      "r": 207,
      "g": 117,
      "b": 39,
      "a": 255,
      "radius": 5
      }	
   ],
  "CustomLayer": [
    {
      "block": "minecraft:redstone_wire",
      "layers": ["bloom"]
    }
  ]
}
```

If I can provide anymore info or context let me know.

**Comment by Yefancy** [comment]
yeah, havent update support yet. I will update fluid supporting version in an hour

**Comment by Saereth** [comment]
Awesome, can't wait, ty for your work on the mod!

**Comment by Yefancy** [comment]
both wiki and CF have been updated
