### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [Low-Drag-MC/Shimmer#45]
### Minecraft Version

1.19.3

### ModLoader

Fabric

### Shimmer version

0.1.14

### Modpack info or mod list(please reduce mod range)

/

### The latest.log file and hs_err_pidXXX if exists

/

### Issue description

Mixin apply for mod shimmer failed shimmer.mixins.json:GameRendererMixin from mod shimmer -> net.minecraft.class_757: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on injectReloadShaders could not find any targets matching 'Lnet/minecraft/class_757;method_34538(Lnet/minecraft/class_3300;)V' in net.minecraft.class_757. Using refmap Shimmer-common-Common-refmap.json [PREINJECT Applicator Phase -> shimmer.mixins.json:GameRendererMixin from mod shimmer -> Prepare Injections ->  -> handler$hlp000$injectReloadShaders(Lnet/minecraft/class_3300;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injectReloadShaders could not find any targets matching 'Lnet/minecraft/class_757;method_34538(Lnet/minecraft/class_3300;)V' in net.minecraft.class_757. Using refmap Shimmer-common-Common-refmap.json [PREINJECT Applicator Phase -> shimmer.mixins.json:GameRendererMixin from mod shimmer -> Prepare Injections ->  -> handler$hlp000$injectReloadShaders(Lnet/minecraft/class_3300;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.lang.Class.getDeclaredMethods(Class.java:2504)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.findMixinMerged(ModIdentifier.java:134)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.getMixinInfo(ModIdentifier.java:166)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromThrowable(ModIdentifier.java:65)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.lambda$identifyFromStacktrace$2(ModIdentifier.java:43)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.visitChildrenThrowables(ModIdentifier.java:53)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromStacktrace(ModIdentifier.java:42)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.lambda$getSuspectedModsOf$0(ModIdentifier.java:35)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at fudge.notenoughcrashes.stacktrace.ModIdentifier.getSuspectedModsOf(ModIdentifier.java:35)
	at net.minecraft.util.crash.CrashReport.md7c38c7$lambda$beforeSystemDetailsAreWritten$1$0(CrashReport:535)
	at net.minecraft.util.SystemDetails.addSection(SystemDetails:66)
	at net.minecraft.util.crash.CrashReport.handler$hca000$beforeSystemDetailsAreWritten(CrashReport:533)
	at net.minecraft.util.crash.CrashReport.addStackTrace(CrashReport:79)
	at net.minecraft.util.crash.CrashReport.asString(CrashReport:134)
	at net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient:889)
	at net.minecraft.client.main.Main.main(Main:215)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by zomb-676** [comment]
1.19.4 will be released soon
1.19.3 will be skiped

**Comment by sternschnaube** [comment]
Nicee to hear, thanks 😊
