### ISSUE TITLE
Crash on world join (Sodium 5.3 incompatibility?)

### ISSUE THREAD

**Issue by MikiP98** [Low-Drag-MC/Shimmer#88]
### Minecraft Version

1.20.1

### ModLoader

Fabric

### Shimmer version

Shimmer-fabric-1.20.1-0.2.3
Shimmer-fabric-1.20.1-0.2.2
Shimmer-fabric-1.20.1-0.2.1

### Modpack info or mod list(please reduce mod range)

Sodium 5.3, Shimmer >0.2.0, LazyDFU, Mod Menu, Fabric API

### The latest.log file and hs_err_pidXXX if exists

[latest.log](https://github.com/Low-Drag-MC/Shimmer/files/13543248/latest.log)
[crash-2023-12-04_08.45.00-client.txt](https://github.com/Low-Drag-MC/Shimmer/files/13543255/crash-2023-12-04_08.45.00-client.txt)

### optifine , Rubidium , flywheel or any rendering related mods. mod version is required.

sodium

### Issue description

When joining a world game crashes with:
java.lang.NullPointerException: Cannot read field "field_44912" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Steps to reproduce

1. Join or create a world

### Other information

I have this issue on 2 different systems.
Version 0.2.0 of shimmer works as intended.

**Comment by Yefancy** [comment]
full log?

**Comment by MikiP98** [comment]
I updated the issue, reduced mod count and provided a log.

**Comment by Yefancy** [comment]
> I updated the issue, reduced mod count and provided a log.

sry, my fault. I missed it

**Comment by AlienXtream** [comment]
getting a similar one to this, though the crash itself is different and from immersive portal (it seems IP does some extra stuff that overwrites the crash report). the logs are much the same and even have the crash report word for word basically.

**Comment by XDom367** [comment]
I also get this crash

**Comment by MikiP98** [comment]
What I'm most interested in, is why the compatibility was downgraded? 
Version 0.2.0 works with Sodium 5.3 and other mods I use in my modpack without any issues.
I understand delaying compatibility but removing it?
@Yefancy Do any dev know why that happened? Can we know the priority of this issue?
I love this and every other mod that improves game visually and is not a demanding "shader", but performance and FPS are still important.
No pressure of course, take your time :)

**Comment by lexi-the-cute** [comment]
yep, sodium causes a crash. i'm currently looking at a ~~double whammy from~~ Sodium ~~and Litematica~~, but this is just Sodium, Fabric API, and Shimmer by themselves. https://mclo.gs/7P3faPD

edit: it's just sodium
